apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: confluent
      image: gcr.io/rpa-devops/confluent
      ports:
        - containerPort: 2092
          name: broker-port
        - containerPort: 8088
          name: ksql-server
      tty: true
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
